version: '3'
services:
  zookeeper:
    container_name: ${COMPOSE_PROJECT_NAME}_zookeeper
    restart: always
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    environment:
      - ZOO_PORT_NUMBER=${ZOOKEEPER_PORT}
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    container_name: ${COMPOSE_PROJECT_NAME}_kafka
    restart: always
    ports:
      - "2${KAFKA_PORT}:2${KAFKA_PORT}"
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT}
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:2${KAFKA_PORT},EXTERNAL://:${KAFKA_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:2${KAFKA_PORT},EXTERNAL://localhost:${KAFKA_PORT}
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1

